# .github/workflows/deploy.yml
name: Deploy Test Page

on:
  push:
    branches:
      - main
      - staging
      - feature-x  # Add any branches you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (or Python/Go/etc if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build  # or your custom build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # your output folder
          destination_dir: ${{ github.ref_name }}  # e.g., staging, feature-x
          keep_files: true
